### ISSUE TITLE
可断断续续打印弹幕信息，但中间有pymongo.errors.ServerSelectionTimeoutError，打印非常不完整

### ISSUE THREAD

**Issue by LifaSun** [gll19920817/douyin_web_live#10]
python main.py + douyin直播链接
Terminal显示的信息：

[+] 2022-04-26 10:04:33【发言】承宝👑: 跳了想睡觉[捂脸]
WebcastMemberMessage persists error
Traceback (most recent call last):
  File "/****/douyin_web_live-main/messages/base.py", line 34, in persists
    if not store.exists({'id': user.id}):
  File "/****/douyin_web_live-main/store/mongo.py", line 26, in exists
    return self.collection.count_documents(condition, limit = 1) != 0
  File "/****/lib/python3.8/site-packages/pymongo/collection.py", line 1827, in count_documents
    return self.__database.client._retryable_read(
  File "/****/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1514, in _retryable_read
    server = self._select_server(
  File "/****/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1346, in _select_server
    server = topology.select_server(server_selector)
  File "/****/lib/python3.8/site-packages/pymongo/topology.py", line 244, in select_server
    return random.choice(self.select_servers(selector,
  File "/****/lib/python3.8/site-packages/pymongo/topology.py", line 202, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/****/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 62675331095c617ae8688b82, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>
[+] 2022-04-26 10:05:03【进入直播间】林林49353 来了

直播间的弹幕信息很多，但是只打印了几条出来，每打印一条，会显示pymongo.errors.ServerSelectionTimeoutError: localhost:27017

 朋友们，请问有遇到过类似问题吗，感谢！

@gll19920817 @FedoraLinux1

**Comment by FedoraLinux1** [comment]
直接把 settings.yml 里的on改 off 试试

**Comment by FedoraLinux1** [comment]
呃，你大概是没安装MongoDB，或者安装了没有成功启动MongoDB
如果 直接把 settings.yml 里的on改 off  之后是成功的，那么就是MongoDB的关系

**Comment by LifaSun** [comment]
感谢解答，刚试了下on改为off, 在运行几十秒之后，还是有pymongo.errors.ServerSelectionTimeoutError: localhost:27017。之后就没再有新的弹幕信息了  （直播间是正常开着的，抖音网页上看到直播间的弹幕是正常的）

同时在运行 mitmdump的那个terminal会有disconnect的信息

127.0.0.1:55358: server disconnect p3.douyinpic.com:443 (183.60.138.227:443)
127.0.0.1:55426: server disconnect p9-webcast.douyinpic.com:443 (124.225.163.120:443)
127.0.0.1:55496: server disconnect lf3-short.bytegoofy.com:443 (113.113.127.240:443)
127.0.0.1:55388: server disconnect mon.snssdk.com:443 (42.56.88.89:443)
127.0.0.1:55396: server disconnect vcs.snssdk.com:443 (27.148.149.147:443)
127.0.0.1:55424: server disconnect mssdk.snssdk.com:443 (1.193.215.229:443)
127.0.0.1:55386: server disconnect log.snssdk.com:443 (125.94.40.190:443)
127.0.0.1:55384: server disconnect pull-flv-l11.douyincdn.com:443 (182.254.61.110:443)
127.0.0.1:55394: server disconnect verify.snssdk.com:443 (61.155.222.94:443)
127.0.0.1:55352: server disconnect lf3-cdn-tos.bytegoofy.com:443 (222.217.94.228:443)
127.0.0.1:55354: server disconnect lf3-short.bytegoofy.com:443 (202.104.186.228:443)
127.0.0.1:55328: server disconnect lf3-cdn-tos.bytegoofy.com:443 (222.217.94.229:443)
127.0.0.1:55324: server disconnect live.douyin.com:443 (117.25.153.241:443)
127.0.0.1:55390: server disconnect mcs.snssdk.com:443 (221.194.141.150:443)

是不是因为抖音有些反爬虫机制什么的导致的disconnect？

**Comment by FedoraLinux1** [comment]
【pymongo.errors.ServerSelectionTimeoutError: localhost:27017】 就只是MongoDB这个数据库连接超时

**Comment by LifaSun** [comment]
好，我看下，蟹蟹

**Comment by gll19920817** [comment]
@FedoraLinux1 哥们辛苦了
