### ISSUE TITLE
wss数据解析求助

### ISSUE THREAD

**Issue by guozi404** [gll19920817/douyin_web_live#14]
���+O�@���|I
                     $��C�b�j��EZAׁ<y�sr�w�H�Yb�a�'V�&�A��*���I
�m��e�i~w����L�������a����㡏#����&      y�<d��2��
                                                 )��
                                                    I$�����_�7��锵U�N&��,n�fl�>SzV�
                                                                                   +��6����:;7FvR7M%�<�EF$
                                                                                                          )C
���yb�#�Y���ʜE��A�@ �ce����p
�C}�tw{R�B��V�zgm�������*��

wss protobuf最后解析出的data字段 是这个乱码 求教怎么再处理

**Comment by gll19920817** [comment]
> ���+O�@���|I $��C�b�j��EZAׁ<y�sr�w�H�Yb�a�'V�&�A��_���I �m��e�i~w����L�������a����㡏#����& y�<d��2�� )�� I$�����_�7��锵U�N&��,n�fl�>SzV� +��6����:;7FvR7M%�<�EF$ )C ���yb�#�Y���ʜE��A�@ �ce����p �C}�tw{R�B��V�zgm�������_��
> 
> wss protobuf最后解析出的data字段 是这个乱码 求教怎么再处理

这。。这个是你直接用mitmproxy捕获到的数据嘛 需要用protoc文件去转义

**Comment by guozi404** [comment]
因为这些数据 都是乱码 不知道怎么推荐里面的字段，其他外部的字段都取到了 就里面不知道怎么处理

**Comment by guozi404** [comment]
> 


因为这些数据 都是乱码 不知道怎么推荐里面的字段，其他外部的字段都取到了 就里面不知道怎么处理

**Comment by wanhaha** [comment]
> > > ���+O�@���|I $��C�b�j��EZAׁ<y�sr�w�H�Yb�a�'V�&�A��_���I �m��e�i~w����L�������a����㡏#����& y�<d��2�� )�� I$�����_�7��锵U�N&��,n�fl�>SzV� +��6����:;7FvR7M%�<�EF$ )C ���yb�#�Y���ʜE��A�@ �ce����p �C}�tw{R�B��V�zgm�������_��
> > > wss protobuf最后解析出的data字段 是这个乱码 求教怎么再处理
> > 
> > 
> > 这。。这个是你直接用mitmproxy捕获到的数据嘛 需要用protoc文件去转义
> 
> 因为这些数据 都是乱码 不知道怎么推荐里面的字段，其他外部的字段都取到了 就里面不知道怎么处理

都是大神，协议一改我都不知道咋办了。。。没头绪了

**Comment by guozi404** [comment]
```
message WssResponse{
  int64 wss_push_room_id = 1;
  int64 wss_push_did = 2;
  int64 wss_push_log_id = 3;
  int64 wss_fetch_ms = 4;
  int64 wss_push_ms = 5;
  string wss_msg_type = 6;
  string pb = 7;
  string data = 8;
  int64 server_time = 9;
  string compress_type = 10;
}
```
wss传输给前段的数据 自己推导了一些 大概这样 可能也有问题，主要是data中的直接乱码 不知道怎么推导了

**Comment by FedoraLinux1** [comment]
> ```
> message WssResponse{
>   int64 wss_push_room_id = 1;
>   int64 wss_push_did = 2;
>   int64 wss_push_log_id = 3;
>   int64 wss_fetch_ms = 4;
>   int64 wss_push_ms = 5;
>   string wss_msg_type = 6;
>   string pb = 7;
>   string data = 8;
>   int64 server_time = 9;
>   string compress_type = 10;
> }
> ```
> 
> wss传输给前段的数据是base64的自己转一下就好，protobuf自己推导了一些 大概这样 可能也有问题，主要是data中的直接乱码 不知道怎么推导了

最后一个data gzip一下就行

**Comment by guozi404** [comment]
```
1: 1
3: 8888
4: 8
5 {
  1: "server_time"
  2: "1652951569203"
}
5 {
  1: "compress_type"
  2: "gzip"
}
7 {
  13: 98
}
8: "\037\213\010\000\000\000\000\000\000\377\000\000\000\377\377\001\000\000\377\377\000\000\000\000\000\000\000\000"
```
8中的数据 是什么编码格式 怎么处理呢 @gll19920817 大佬 知道吗

**Comment by FedoraLinux1** [comment]
> ```
> 1: 1
> 3: 8888
> 4: 8
> 5 {
>   1: "server_time"
>   2: "1652951569203"
> }
> 5 {
>   1: "compress_type"
>   2: "gzip"
> }
> 7 {
>   13: 98
> }
> 8: "\037\213\010\000\000\000\000\000\000\377\000\000\000\377\377\001\000\000\377\377\000\000\000\000\000\000\000\000"
> ```
> 
> 8中的数据 是什么编码格式 怎么处理呢 @gll19920817 大佬 知道吗

我已经提交了代码，但是很抱歉，对git的推送不是很了解，所以推送到了我的那边：https://github.com/FedoraLinux1/douyin_web_live

**Comment by gll19920817** [comment]
> > ```
> > 1: 1
> > 3: 8888
> > 4: 8
> > 5 {
> >   1: "server_time"
> >   2: "1652951569203"
> > }
> > 5 {
> >   1: "compress_type"
> >   2: "gzip"
> > }
> > 7 {
> >   13: 98
> > }
> > 8: "\037\213\010\000\000\000\000\000\000\377\000\000\000\377\377\001\000\000\377\377\000\000\000\000\000\000\000\000"
> > ```
> > 
> > 8中的数据 是什么编码格式 怎么处理呢 @gll19920817 大佬 知道吗
> 
> 我已经提交了代码，但是很抱歉，对git的推送不是很了解，所以推送到了我的那边：https://github.com/FedoraLinux1/douyin_web_live

好 readme加个了解 我把这个仓库设为只读了

**Comment by FedoraLinux1** [comment]
> > ���+O�@���|I $��C�b�j��EZAׁ<y�sr�w�H�Yb�a�'V�&�A��_���I �m��e�i~w����L�������a����㡏#����& y�<d��2�� )�� I$�����_�7��锵U�N&��,n�fl�>SzV� +��6����:;7FvR7M%�<�EF$ )C ���yb�#�Y���ʜE��A�@ �ce����p �C}�tw{R�B��V�zgm�������_��
> > wss protobuf最后解析出的data字段 是这个乱码 求教怎么再处理
> 
> 这。。这个是你直接用mitmproxy捕获到的数据嘛 需要用protoc文件去转义

我要怎么样才通过合作人的方式提交？

**Comment by guozi404** [comment]
@FedoraLinux1 大佬data中 求教 \037\213\010\000\000\000\000\000\000\377\354\225Kl 这种数据 是什么格式

**Comment by FedoraLinux1** [comment]
> @FedoraLinux1 大佬data中 求教 \037\213\010\000\000\000\000\000\000\377\354\225Kl 这种数据 是什么格式

你看下最新的code，里面有的

**Comment by guozi404** [comment]
> > @FedoraLinux1 大佬data中 求教 \037\213\010\000\000\000\000\000\000\377\354\225Kl 这种数据 是什么格式
> 
> 你看下最新的code，里面有的

我是用GO去写的，我看是gzip.decompress解压去处理 但是我处理后 解析不了

**Comment by FedoraLinux1** [comment]
> > > @FedoraLinux1 大佬data中 求教 \037\213\010\000\000\000\000\000\000\377\354\225Kl 这种数据 是什么格式
> > 
> > 
> > 你看下最新的code，里面有的
> 
> 我是用GO去写的，我看是gzip.decompress解压去处理 但是我处理后 解析不了
data就是之前的http的数据经过gzip压缩后的，所以经过第一次的proto解析后，8里边的data再gzip解压一次就行了

**Comment by guozi404** [comment]
> > > > @FedoraLinux1 大佬data中 求教 \037\213\010\000\000\000\000\000\000\377\354\225Kl 这种数据 是什么格式
> > > 
> > > 
> > > 你看下最新的code，里面有的
> > 
> > 
> > 我是用GO去写的，我看是gzip.decompress解压去处理 但是我处理后 解析不了
> > data就是之前的http的数据经过gzip压缩后的，所以经过第一次的proto解析后，8里边的data再gzip解压一次就行了

好的  谢谢
