### ISSUE TITLE
离开直播间有办法得到不？相当于需要知道最新直播间在线人撒

### ISSUE THREAD

**Issue by vinfolhu** [gll19920817/douyin_web_live#17]

**Comment by FedoraLinux1** [comment]
memberCount

**Comment by FedoraLinux1** [comment]
[这个图里黄色字体不就是么？](https://github.com/FedoraLinux1/douyin_web_live/blob/main/20220519190807.png?raw=true)

**Comment by vinfolhu** [comment]
有在线人数清单吗？需要知道谁离开了。然后可以从清单中清除出去。现在只有总数没啥

**Comment by FedoraLinux1** [comment]
> 有在线人数清单吗？需要知道谁离开了。然后可以从清单中清除出去。现在只有总数没啥

应该是不大可能有这种的，一个用户离开直播间，是他客户端断开连接，不可能反馈给所有用户知道（也不需要这种设计）。
另外app上一个直播间最多显示200名在线用户的情况，假如有2万人在线观看，剩下的也不会显示。
ps，web上也不显示200名在线用户，只有一个数字

**Comment by gll19920817** [comment]
> 有在线人数清单吗？需要知道谁离开了。然后可以从清单中清除出去。现在只有总数没啥

一个浏览器打开直播间有可能抖音服务器推给你的只有部分数据 所以这里不适合做太精确的数据统计
