### ISSUE TITLE
弹幕时间长了，延时好大

### ISSUE THREAD

**Issue by GezeZhou** [gll19920817/douyin_web_live#21]
大佬，这个运行时间长一点，延时好大，弹幕多的时候，运行30分钟，延时可能有10来分钟，是不是我设置有问题？
如果拿来做游戏的话，有什么办法能把延时优化？只要弹幕和礼物信息，别的不要。
谢谢！

**Comment by FedoraLinux1** [comment]
修改一下文件：..\messages\utils.py
{def decodeMsg(messages):}里，不需要的elif都删了

**Comment by GezeZhou** [comment]
> 修改一下文件：..\messages\utils.py {def decodeMsg(messages):}里，不需要的elif都删了

谢谢大佬，延时有办法改善吗

**Comment by gll19920817** [comment]
> > 修改一下文件：..\messages\utils.py {def decodeMsg(messages):}里，不需要的elif都删了
> 
> 谢谢大佬，延时有办法改善吗，别的删了，延时还是很大

web端直播间看到的弹幕都是抖音服务器推过来的 所以延时的问题感觉没有办法呢 :(

**Comment by GezeZhou** [comment]
> > > > 修改一下文件：..\messages\utils.py {def decodeMsg(messages):}里，不需要的elif都删了
> > > 
> > > 
> > > 谢谢大佬，延时有办法改善吗，别的删了，延时还是很大
> > 
> > 
> > web端直播间看到的弹幕都是抖音服务器推过来的 所以延时的问题感觉没有办法呢 :(
> 
> 谢谢回复！但是弹幕多，人多的时候，延时会到10多分钟，今天测了:( ，是不是我的环境有问题
大佬，我说的可能有歧义，我说的延时是我在直播间看到了的别人发的弹幕，弹幕多的时候，抓取这边要过10多分钟才显示出来

**Comment by gll19920817** [comment]
> > > > > 修改一下文件：..\messages\utils.py {def decodeMsg(messages):}里，不需要的elif都删了
> > > > 
> > > > 
> > > > 谢谢大佬，延时有办法改善吗，别的删了，延时还是很大
> > > 
> > > 
> > > web端直播间看到的弹幕都是抖音服务器推过来的 所以延时的问题感觉没有办法呢 :(
> > 
> > 
> > 谢谢回复！但是弹幕多，人多的时候，延时会到10多分钟，今天测了:( ，是不是我的环境有问题
> > 大佬，我说的可能有歧义，我说的延时是我在直播间看到了的别人发的弹幕，弹幕多的时候，抓取这边要过10多分钟才显示出来，是从直播间看到一条弹幕到抓取这边显示这条弹幕，时间相差了10多分钟，不是输入弹幕到显示弹幕的延时。感觉是抓取这边显示频率太慢了，导致累积的延时，如果是的话，能不能提高刷新率，谢谢大佬！

嗯嗯 懂了 你把scripts/watcher.py 26行time.sleep(0.2) 注释了试下

**Comment by GezeZhou** [comment]
> 



> > > > > > 修改一下文件：..\messages\utils.py {def decodeMsg(messages):}里，不需要的elif都删了
> > > > > 
> > > > > 
> > > > > 谢谢大佬，延时有办法改善吗，别的删了，延时还是很大
> > > > 
> > > > 
> > > > web端直播间看到的弹幕都是抖音服务器推过来的 所以延时的问题感觉没有办法呢 :(
> > > 
> > > 
> > > 谢谢回复！但是弹幕多，人多的时候，延时会到10多分钟，今天测了:( ，是不是我的环境有问题
> > > 大佬，我说的可能有歧义，我说的延时是我在直播间看到了的别人发的弹幕，弹幕多的时候，抓取这边要过10多分钟才显示出来，是从直播间看到一条弹幕到抓取这边显示这条弹幕，时间相差了10多分钟，不是输入弹幕到显示弹幕的延时。感觉是抓取这边显示频率太慢了，导致累积的延时，如果是的话，能不能提高刷新率，谢谢大佬！
> 
> 嗯嗯 懂了 你把scripts/watcher.py 26行time.sleep(0.2) 注释了试下

谢谢大佬这么晚还回复，刚试了，改善了很多，试运行了半小时，直播间人数5000左右的情况下，开始延时很小，到后面延时大概2-3分钟

**Comment by FedoraLinux1** [comment]
> > 
> 
> > > > > > > 修改一下文件：..\messages\utils.py {def decodeMsg(messages):}里，不需要的elif都删了
> > > > > > 
> > > > > > 
> > > > > > 谢谢大佬，延时有办法改善吗，别的删了，延时还是很大
> > > > > 
> > > > > 
> > > > > web端直播间看到的弹幕都是抖音服务器推过来的 所以延时的问题感觉没有办法呢 :(
> > > > 
> > > > 
> > > > 谢谢回复！但是弹幕多，人多的时候，延时会到10多分钟，今天测了:( ，是不是我的环境有问题
> > > > 大佬，我说的可能有歧义，我说的延时是我在直播间看到了的别人发的弹幕，弹幕多的时候，抓取这边要过10多分钟才显示出来，是从直播间看到一条弹幕到抓取这边显示这条弹幕，时间相差了10多分钟，不是输入弹幕到显示弹幕的延时。感觉是抓取这边显示频率太慢了，导致累积的延时，如果是的话，能不能提高刷新率，谢谢大佬！
> > 
> > 
> > 嗯嗯 懂了 你把scripts/watcher.py 26行time.sleep(0.2) 注释了试下
> 
> 谢谢大佬这么晚还回复，刚试了，改善了很多，试运行了半小时，直播间人数5000左右的情况下，开始延时很小，到后面延时大概2-3分钟

清空下MongoDB下user的集合，以及给use新建用户id索引

**Comment by FedoraLinux1** [comment]
> > > 
> > 
> > 
> > > > > > > > 修改一下文件：..\messages\utils.py {def decodeMsg(messages):}里，不需要的elif都删了
> > > > > > > 
> > > > > > > 
> > > > > > > 谢谢大佬，延时有办法改善吗，别的删了，延时还是很大
> > > > > > 
> > > > > > 
> > > > > > web端直播间看到的弹幕都是抖音服务器推过来的 所以延时的问题感觉没有办法呢 :(
> > > > > 
> > > > > 
> > > > > 谢谢回复！但是弹幕多，人多的时候，延时会到10多分钟，今天测了:( ，是不是我的环境有问题
> > > > > 大佬，我说的可能有歧义，我说的延时是我在直播间看到了的别人发的弹幕，弹幕多的时候，抓取这边要过10多分钟才显示出来，是从直播间看到一条弹幕到抓取这边显示这条弹幕，时间相差了10多分钟，不是输入弹幕到显示弹幕的延时。感觉是抓取这边显示频率太慢了，导致累积的延时，如果是的话，能不能提高刷新率，谢谢大佬！
> > > 
> > > 
> > > 嗯嗯 懂了 你把scripts/watcher.py 26行time.sleep(0.2) 注释了试下
> > 
> > 
> > 谢谢大佬这么晚还回复，刚试了，改善了很多，试运行了半小时，直播间人数5000左右的情况下，开始延时很小，到后面延时大概2-3分钟
> 
> 清空下MongoDB下user的集合，以及给use新建用户id索引

或者测试的时候，将{ settings.yml }的mongo的on设置为其他的，看看是不是存在延迟，如果没有延迟就按照上面说的清空集合

**Comment by GezeZhou** [comment]
> > > > 
> > > 
> > > 
> > > > > > > > > 修改一下文件：..\messages\utils.py {def decodeMsg(messages):}里，不需要的elif都删了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 谢谢大佬，延时有办法改善吗，别的删了，延时还是很大
> > > > > > > 
> > > > > > > 
> > > > > > > web端直播间看到的弹幕都是抖音服务器推过来的 所以延时的问题感觉没有办法呢 :(
> > > > > > 
> > > > > > 
> > > > > > 谢谢回复！但是弹幕多，人多的时候，延时会到10多分钟，今天测了:( ，是不是我的环境有问题
> > > > > > 大佬，我说的可能有歧义，我说的延时是我在直播间看到了的别人发的弹幕，弹幕多的时候，抓取这边要过10多分钟才显示出来，是从直播间看到一条弹幕到抓取这边显示这条弹幕，时间相差了10多分钟，不是输入弹幕到显示弹幕的延时。感觉是抓取这边显示频率太慢了，导致累积的延时，如果是的话，能不能提高刷新率，谢谢大佬！
> > > > 
> > > > 
> > > > 嗯嗯 懂了 你把scripts/watcher.py 26行time.sleep(0.2) 注释了试下
> > > 
> > > 
> > > 谢谢大佬这么晚还回复，刚试了，改善了很多，试运行了半小时，直播间人数5000左右的情况下，开始延时很小，到后面延时大概2-3分钟
> > 
> > 
> > 清空下MongoDB下user的集合，以及给use新建用户id索引
> 
> 或者测试的时候，将{ settings.yml }的mongo的on设置为其他的，看看是不是存在延迟，如果没有延迟就按照上面说的清空集合

我是在Mongo设置成off的状态下测试的(T⌓T)，不是mongodb设置的问题

**Comment by FedoraLinux1** [comment]
可能一开始,我就用[ImDisk]虚拟内存做硬盘来作为监控目录,所以一直没出现过这个问题
刚才监控一个2w人的直播间半个多小时,也没有出现弹幕延迟的情况,你也可以试试看.
如果还有延迟的话,是不是考虑下网络问题?

**Comment by GezeZhou** [comment]
> 可能一开始,我就用[ImDisk]虚拟内存做硬盘来作为监控目录,所以一直没出现过这个问题 刚才监控一个2w人的直播间半个多小时,也没有出现弹幕延迟的情况,你也可以试试看. 如果还有延迟的话,是不是考虑下网络问题?

谢谢，我试试看

**Comment by jesseyang0626** [comment]
延时是因为一次循环只从queue里取一个。你可以试试一次循环直接把queue的全部拿出来处理掉

**Comment by GezeZhou** [comment]
> > 可能一开始,我就用[ImDisk]虚拟内存做硬盘来作为监控目录,所以一直没出现过这个问题 刚才监控一个2w人的直播间半个多小时,也没有出现弹幕延迟的情况,你也可以试试看. 如果还有延迟的话,是不是考虑下网络问题?
> 
> 谢谢，我试试看
我用服务器试了，也是一样:( 
我运行的时候有这个错误，是不是和这个有关系: 

C:\Users\ww\Documents\douyindanmu\douyin_web_live-main>python main.py https://live.douyin.com/360122601221

DevTools listening on ws://127.0.0.1:50270/devtools/browser/7ebffa99-0d90-4481-8f9a-f43ba4c83432
[0531/140236.167:INFO:CONSOLE(1)] "%c [object HTMLImageElement]", source: https://live.douyin.com/360122601221 (1)
[0531/140237.991:ERROR:web_contents_delegate.cc(232)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0531/140237.991:ERROR:web_contents_delegate.cc(232)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0531/140238.855:INFO:CONSOLE(6)] "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu", source: https://lf3-cdn-tos.bytegoofy.com/goofy/douyin_live/resource/chunk/bytejs.3ebb9035.js (6)

[+] 2022-05-31 14:02:40【发言】E***: 白色裙子S码能上吗？

[+] 2022-05-31 14:02:40【发言】默***: 男生能穿吗

[+] 2022-05-31 14:02:40【发言】红***: 长袖

[+] 2022-05-31 14:02:40【发言】用***: 夕拉面霜

[+] 2022-05-31 14:02:40【发言】0***: [赞][赞][赞][赞]

**Comment by GezeZhou** [comment]
> 延时是因为一次循环只从queue里取一个。你可以试试一次循环直接把queue的全部拿出来处理掉

我是菜鸟，能不能指点一下怎么改，谢谢 : )

**Comment by FedoraLinux1** [comment]
船新版本有效解决弹幕延迟问题
