### ISSUE TITLE
请问下这个错误：AttributeError: 'WebSocketFlow' object has no attribute 'request'

### ISSUE THREAD

**Issue by vinfolhu** [gll19920817/douyin_web_live#22]
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/18110163/170628822-e7f4b218-e057-4778-a441-fc4ca5cdf553.png">

127.0.0.1:57816 <- WebSocket 2 message <- webcast3-ws-web-lf.douyin.com:443/webcast/im/push/?aid=6383&app_name=douyin_web&browser_language=zh-CN&browser_name=Mozilla&browser_online=true&browser_platform=Linux%20x86_64&browser_version=5.0%20%28X11%3B%20Linux%20x86_64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20HeadlessChrome%2F102.0.5005.61%20Safari%2F537.36&compress=gzip&cookie_enabled=true&cursor=1653616575752_1_1_1&device_platform=web&did_rule=3&identity=audience&imprp=u4-_rCnAjlCTU&live_id=1&room_id=7101639909236165384&screen_height=600&screen_width=800&tz_name=Asia%2FShanghai&update_version_code=0.0.13&version_code=180800&webcast_sdk_version=0.0.13
Addon error: Traceback (most recent call last):
  File "scripts/mitmproxy.py", line 18, in websocket_message
    re_c = re.search('webcast3-ws-web-.*\.douyin\.com', flow.request.host)
AttributeError: 'WebSocketFlow' object has no attribute 'request'

在Linuxbu s部署出现的这个错误。网上没找到相关信息。能否帮忙看下，感谢！

**Comment by FedoraLinux1** [comment]
什么系统,什么环境?
