### ISSUE TITLE
启动失败了呢？

### ISSUE THREAD

**Issue by liuyang1128** [gll19920817/douyin_web_live#33]
![image](https://user-images.githubusercontent.com/12913942/173725160-46a621cd-8432-4b20-9758-eaf4250c1a80.png)
![image](https://user-images.githubusercontent.com/12913942/173725263-9893cd83-286d-45c4-867e-3ebd5b1b5cb7.png)

**Comment by FedoraLinux1** [comment]
> mitmproxy~=8.0.0
> protobuf<3.20

这两个版本正确吗?

**Comment by liuyang1128** [comment]
![image](https://user-images.githubusercontent.com/12913942/173982499-e6b30694-0a80-4464-a81c-cbc5ea2e383a.png)
已经按照这个插件下载了，还是显示变量不存在

**Comment by liuyang1128** [comment]
辛苦给看一下

**Comment by FedoraLinux1** [comment]
> 辛苦给看一下

有没有解决？没有解决的话，加我Q：7625926
