### ISSUE TITLE
ImportError: DLL load failed while importing _brotli: 拒绝访问。

### ISSUE THREAD

**Issue by WangDrama** [gll19920817/douyin_web_live#35]
我运行main.py报拒绝访问，我已经把appdata下面的安全里面加了everyone 并且完全控制
![`J0`3`WTHT@LV~0K_~42}J7](https://user-images.githubusercontent.com/33739071/173997331-fabe5a3e-e9d0-4c85-b54e-c185dd823f6f.png)

![SNSY LNFDXSAWSVG D9FIYM](https://user-images.githubusercontent.com/33739071/173997299-4fb8717b-0019-4623-aba7-453bc4bd516b.png)

**Comment by WangDrama** [comment]
> 使用Python3.9试试看, 路径中不要有中文

可以了，也不知道具体哪个原因，应该是版本原因

**Comment by WangDrama** [comment]
> > 使用Python3.9试试看, 路径中不要有中文
> 
> 可以了，也不知道具体哪个原因，应该是版本原因

不对，这个问题还是存在，换了python版本，路径也没有中文的，按论坛说的也安装了vc_redist.x64.exe，不知道到底什么导致的

**Comment by FedoraLinux1** [comment]
试试看 用conda来创建虚拟环境来运行呢

**Comment by WangDrama** [comment]
> 

hao ,wo试试

**Comment by WangDrama** [comment]
> 试试看 用conda来创建虚拟环境来运行呢

可以了，虚拟环境可以运行
