### ISSUE TITLE
怎么获取评论用户的id

### ISSUE THREAD

**Issue by zwb3707811** [gll19920817/douyin_web_live#36]

**Comment by FedoraLinux1** [comment]
评论用户的id？？？

**Comment by zwb3707811** [comment]
是的 但那个直播间是加密的直播间， 平常直播间我看是有

**Comment by FedoraLinux1** [comment]
> 是的 但那个直播间是加密的直播间， 平常直播间我看是有

昵称带*号，无法获取

**Comment by zwb3707811** [comment]
> > 是的 但那个直播间是加密的直播间， 平常直播间我看是有
> 
> 昵称带*号，无法获取

好的 谢谢

**Comment by yao97** [comment]
> 

如果名称没有带*号的 是否可以抓呢？
