### ISSUE TITLE
送礼物的message，好像没有显示出来，在哪里添加代码可以显示出来

### ISSUE THREAD

**Issue by aliffffff** [gll19920817/douyin_web_live#38]

**Comment by FedoraLinux1** [comment]
应该是自动显示，不需要再添加代码。
如果按照默认配置的话，是可以看到浏览器和控制台窗口里都有弹幕信息，把这些截图看一下？

**Comment by zhidd** [comment]
![image](https://user-images.githubusercontent.com/11773303/174513004-aee506ea-d551-4a90-b514-8d0832b36b68.png)
图中黄色的字体的信息，没有在控制台显示

**Comment by FedoraLinux1** [comment]
> ![image](https://user-images.githubusercontent.com/11773303/174513004-aee506ea-d551-4a90-b514-8d0832b36b68.png) 图中黄色的字体的信息，没有在控制台显示 **### 送出了{红心}X1 没有在控制台显示**

这倒是很奇怪，不应该的，能否远程看看？
