### ISSUE TITLE
请问如何输出进入直播间的数据

### ISSUE THREAD

**Issue by yao97** [gll19920817/douyin_web_live#43]
现在可以正常输出弹幕数据和礼物数据，但是蓝色框中的直播间进入的这些数据不知道从哪里修改可以输出。
![1661018638027](https://user-images.githubusercontent.com/20462086/185760479-8b7de327-4637-47bb-bae8-389d4710f790.png)

望回复
感谢您的开源

**Comment by gll19920817** [comment]
可以在messages/member.py __str__方法修改

**Comment by yao97** [comment]
我想把直播间进入用户信息也输出到xml文件中
直接在output/xml.py中添加对应代码就可以了么？尝试直接在xml.py中添加还是失败。
按照
