### ISSUE TITLE
1

### ISSUE THREAD

**Issue by cicadaWan** [gll19920817/douyin_web_live#5]
跑不起来，一直好像被拒绝访问一样，搞不懂

**Comment by xiaorui16888** [comment]
可以跑啊。

**Comment by gll19920817** [comment]
[cry] 报什么错呢

**Comment by gll19920817** [comment]
> 可以跑啊。

蟹蟹٩('ω')و

**Comment by WangDrama** [comment]
> 跑不起来，一直好像被拒绝访问一样，搞不懂

我也是，报拒绝访问，已经把appdata目录改成everyone 完全控制了 但还是报错
    import _brotli
ImportError: DLL load failed while importing _brotli: 拒绝访问。

![image](https://user-images.githubusercontent.com/33739071/173984183-f02edfbd-f7cc-439a-b46e-378e0ecfe3d6.png)
