### ISSUE TITLE
pip install requirements.txt 报错找不到

### ISSUE THREAD

**Issue by theajack** [gll19920817/douyin_web_live#6]
请问pip install requirements.txt 报错找不到怎么解

<img width="888" alt="image" src="https://user-images.githubusercontent.com/23377279/163677443-3c4a79fb-16df-4ee1-9e57-51a9345305b1.png">

**Comment by yisier** [comment]
pip install -r requirements.txt -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com

**Comment by gll19920817** [comment]
> pip install -r requirements.txt -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com

蟹蟹
