### ISSUE TITLE
比如：同时打开A或者B直播间，怎么解决mitmproxy监控错误的问题？

### ISSUE THREAD

**Issue by FedoraLinux1** [gll19920817/douyin_web_live#7]
rt
尝试搜索了一下，没有找到相同的资料。
仅仅做到了，复制两份代码到不同的目录，然后监控不同的端口才解决这个问题

ps，在复制了两份代码之后，偶尔还会出现自定义目录下，代码不删除response返回的文件

**Comment by gll19920817** [comment]
大兄弟你说的这个问题感觉可以让代码根据直播间链接ID来生成对应的http响应保存的目录 然后代码监控生成的目录就可以 具体实现你可以考虑下

**Comment by FedoraLinux1** [comment]
> 



> 大兄弟你说的这个问题感觉可以让代码根据直播间链接ID来生成对应的http响应保存的目录 然后代码监控生成的目录就可以 具体实现你可以考虑下

这个思路可以去试试看.
ps. 关于不删除response返回的文件, 经过调试发现是因为在mongodb插入数据的时候, 当集合的文档数超过百万条后, 查询时间过长导致的, 在修改了mongodb的最大连接池以及给相关集合做了索引之后, 有所改善, 但并未完全解决问题, 偶尔依旧会有不完全删除的清空.
ps1. 感谢作者开源, 这个项目让我学到了不少
