### ISSUE TITLE
mitmproxy运行时，显示Client TLS handshake failed

### ISSUE THREAD

**Issue by LifaSun** [gll19920817/douyin_web_live#8]
在执行mitmdump -s mitmproxy.py时

Loading script mitmproxy.py
Proxy server listening at http://*:8080
127.0.0.1:33544: client connect
127.0.0.1:33544: server connect live.douyin.com:443 (59.37.80.229:443)
127.0.0.1:33544: Client TLS handshake failed. The client does not trust the proxy's certificate for live.douyin.com (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]))
127.0.0.1:33544: client disconnect
127.0.0.1:33544: server disconnect live.douyin.com:443 (59.37.80.229:443)

显示证书错误，请问如何解决？非常感谢！

**Comment by FedoraLinux1** [comment]
试试看 在[webdriver]
添加一个忽略证书的设置。
    # 添加一个忽略证书
    chrome_options.add_argument('-ignore-certificate-errors')
    chrome_options.add_argument('-ignore -ssl-errors')

**Comment by LifaSun** [comment]
解决了，太感谢了！

> 试试看 在[webdriver] 添加一个忽略证书的设置。 # 添加一个忽略证书 chrome_options.add_argument('-ignore-certificate-errors') chrome_options.add_argument('-ignore -ssl-errors')
