### ISSUE TITLE
我这边老是报ssl问题咋解决呀

### ISSUE THREAD

**Issue by luxiaolan6373** [gll19920817/douyin_web_live#9]
我这边老是报ssl问题咋解决呀 就是什么都搞对了..就这一个问题了.windows的

**Comment by FedoraLinux1** [comment]
安装【mitmproxy】 证书。Windows一般位置在【C:\Users\YouerPcName\.mitmproxy】

或者 试试看 在[webdriver]
添加一个忽略证书的设置。
# 添加一个忽略证书
chrome_options.add_argument('-ignore-certificate-errors')
chrome_options.add_argument('-ignore -ssl-errors')

**Comment by luxiaolan6373** [comment]
好的,我试试谢谢

**Comment by luxiaolan6373** [comment]
还是这样
我已经添加了您说的代码了 也安装了证书了  
 [0426/114440.305:ERROR:web_contents_delegate.cc(233)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0426/114440.305:ERROR:web_contents_delegate.cc(233)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
然后依然报目标计算机积极拒绝  的错误  然后mitmproxy那边是是有请求数据的.那边是没问题的

**Comment by luxiaolan6373** [comment]
好的我试试 谢谢回复了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月25日(星期一) 晚上10:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gll19920817/douyin_web_live] 我这边老是报ssl问题咋解决呀 (Issue #9)





 
安装【mitmproxy】 证书。Windows一般位置在【C:\Users\YouerPcName.mitmproxy】
 
或者 试试看 在[webdriver]
 添加一个忽略证书的设置。
 
添加一个忽略证书
 
chrome_options.add_argument('-ignore-certificate-errors')
 chrome_options.add_argument('-ignore -ssl-errors')
